# Generated by Django 5.0.3 on 2024-05-07 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('area_country', models.PositiveIntegerField()),
                ('hymn', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"states"."country"',
            },
        ),
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date_of_feast', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"states"."feast"',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('coordinates', models.TextField(blank=True, null=True)),
                ('area_city', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
            options={
                'db_table': '"states"."city"',
            },
        ),
        migrations.CreateModel(
            name='CountryToFeast',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
                ('feast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.feast')),
            ],
            options={
                'db_table': '"states"."country_to_feast"',
                'unique_together': {('country', 'feast')},
            },
        ),
    ]
