# Generated by Django 5.0.3 on 2024-05-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='feast',
            options={'verbose_name': 'feast', 'verbose_name_plural': 'feasts'},
        ),
        migrations.AddField(
            model_name='feast',
            name='countries',
            field=models.ManyToManyField(through='myapp.CountryToFeast', to='myapp.country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='countrytofeast',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='countrytofeast',
            name='feast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.feast', verbose_name='feast'),
        ),
    ]
