# Generated by Django 5.0.3 on 2024-06-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_countryuser_user_countryuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='countries',
            field=models.ManyToManyField(null=True, through='myapp.CountryToFeast', to='myapp.country', verbose_name='countries'),
        ),
    ]
