# Generated by Django 5.0.3 on 2024-06-09 17:43

import django.db.models.deletion
import myapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0007_alter_feast_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateTimeField(blank=True, default=myapp.models.get_datetime, null=True, validators=[myapp.models.check_created], verbose_name='created')),
                ('modified', models.DateTimeField(blank=True, default=myapp.models.get_datetime, null=True, validators=[myapp.models.check_modified], verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': '"states"."client"',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.CreateModel(
            name='CountryClient',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=myapp.models.get_datetime, null=True, validators=[myapp.models.check_created], verbose_name='created')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client', verbose_name='client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'relationship country client',
                'verbose_name_plural': 'relationships country client',
                'db_table': '"states"."country_client"',
                'unique_together': {('country', 'client')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='countries',
            field=models.ManyToManyField(through='myapp.CountryClient', to='myapp.country', verbose_name='countries'),
        ),
        migrations.DeleteModel(
            name='CountryUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
