# Generated by Django 5.0.3 on 2024-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_client_remove_user_countries_remove_user_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area_country',
            field=models.PositiveIntegerField(default=0, verbose_name='area country'),
        ),
    ]
